## ext2fs.h (e2fsprogs) bindings for Nim autogenerated via Futhark
import pkg/futhark

importc:
  path "/usr/include/ext2fs" # TODO: nixos support
  "ext2fs.h"

{.passL: gorge("pkg-config --libs ext2fs").}
